using System;
using System.Xml.Serialization;

namespace CaptivityEvents.Enums
{
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    [Serializable]
    public enum RestrictedListOfFlags
    {
        WaitingMenu,
        CanOnlyBeTriggeredByOtherEvent,
        Common,
        Femdom,
        Bestiality,
        Prostitution,
        Romance,
        Slavery,
        Straight,
        Lesbian,
        Overwriteable,
        Gay,
        VisitedByCaravan,
        VisitedByLord,
        DuringSiege,
        DuringRaid,
        LocationTravellingParty,
        LocationCaravan,
        LocationPartyInTown,
        LocationDungeon,
        LocationHideout,
        LocationTavern,
        LocationVillage,
        LocationCity,
        LocationCastle,
        TimeNight,
        TimeDay,
        HeroGenderIsFemale,
        HeroGenderIsMale,
        Random,
        Captor,
        Captive,
        CaptiveIsHero,
        CaptiveIsNonHero,
        CaptorIsHero,
        CaptorGenderIsFemale,
        CaptorGenderIsMale,
        CaptorHaveSpouse,
        CaptorNotHaveSpouse,
        HeroOwnedByNotable,
        HeroNotOwnedByNotable,
        HeroHaveOffspring,
        HeroHaveSpouse,
        HeroNotHaveSpouse,
        HeroIsPregnant,
        HeroIsNotPregnant,
        HeroIsProstitute,
        HeroIsNotProstitute,
        HeroIsSlave,
        HeroIsNotSlave,
        HeroIsOwned,
        HeroIsNotOwned,
        HeroOwnsFief,
        HeroIsClanLeader,
        DeathAlternative,
        CaptureAlternative,
        DesertionAlternative,
        MarriageAlternative,
        DuringPlayerRaid,
        SeasonSpring,
        SeasonWinter,
        SeasonSummer,
        SeasonFall,
        CaptivesOutNumber,
        HeroIsFactionLeader,
        PlayerIsNotBusy
    }
}